<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MinhHuy.AIOffice.Core.Api</RootNamespace>
    <AssemblyName>MinhHuy.AIOffice.Core.Api</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Shared.Contracts\Shared.Contracts.csproj" />
    <ProjectReference Include="..\Platform.Persistence\Platform.Persistence.csproj" />
  </ItemGroup>
</Project>
