// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhHuy.AIOffice.Platform.Persistence;

#nullable disable

namespace MinhHuy.AIOffice.Platform.Persistence.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20261010031308_AddGroupIngressInbox")]
    partial class AddGroupIngressInbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("aioffice")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.CompanyAdministratorAuditRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AfterAdministrator")
                        .HasColumnType("bit");

                    b.Property<string>("AfterRolesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("AfterVersion")
                        .HasColumnType("bigint");

                    b.Property<bool>("BeforeAdministrator")
                        .HasColumnType("bit");

                    b.Property<string>("BeforeRolesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BeforeVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantId", "CompanyId", "Id");

                    b.HasIndex("TenantId", "ActorUserId");

                    b.HasIndex("TenantId", "CompanyId", "OperationId")
                        .IsUnique();

                    b.HasIndex("TenantId", "CompanyId", "TargetUserId");

                    b.ToTable("CompanyAdministratorAudits", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_CompanyAdministratorAudits_Versions", "[BeforeVersion] > 0 AND [AfterVersion] >= [BeforeVersion]");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.CompanyMembershipAccessAuditRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AfterActive")
                        .HasColumnType("bit");

                    b.Property<long>("AfterVersion")
                        .HasColumnType("bigint");

                    b.Property<bool>("BeforeActive")
                        .HasColumnType("bit");

                    b.Property<long>("BeforeVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantId", "CompanyId", "Id");

                    b.HasIndex("TenantId", "ActorUserId");

                    b.HasIndex("TenantId", "CompanyId", "OperationId")
                        .IsUnique();

                    b.HasIndex("TenantId", "CompanyId", "TargetUserId");

                    b.ToTable("CompanyMembershipAccessAudits", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_CompanyMembershipAccessAudits_Versions", "[BeforeVersion] > 0 AND [AfterVersion] >= [BeforeVersion]");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.CompanyMembershipRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("TenantId", "CompanyId", "UserId");

                    b.HasIndex("TenantId", "UserId");

                    b.ToTable("CompanyMemberships", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_CompanyMemberships_Version", "[Version] > 0");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("Companies", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.CustomerSlaPolicyRevisionRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("PolicyVersion")
                        .HasColumnType("bigint");

                    b.Property<long>("AuthorityVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("EffectiveAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PriorityCeiling")
                        .HasColumnType("int");

                    b.Property<int>("SchedulerPriority")
                        .HasColumnType("int");

                    b.Property<string>("ServiceLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TenantId", "CompanyId", "UserId", "PolicyVersion");

                    b.HasIndex("TenantId", "CompanyId", "UserId", "EffectiveAtUtc")
                        .HasDatabaseName("IX_CustomerSlaPolicyRevisions_Current");

                    b.ToTable("CustomerSlaPolicyRevisions", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.DataSourceFailoverOperationPolicyRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Operation")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("TenantId", "CompanyId", "DataSourceId", "Operation", "Version");

                    b.HasIndex("TenantId", "CompanyId", "DataSourceId", "Operation", "EffectiveAt");

                    b.ToTable("DataSourceFailoverOperationPolicies", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_DataSourceFailoverOperationPolicies_Version", "[Version] > 0");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.DataSourceRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowWrite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ConnectionSecretReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LogicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaxConcurrency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.HasKey("TenantId", "CompanyId", "Id");

                    b.HasIndex("TenantId", "CompanyId", "LogicalName")
                        .IsUnique();

                    b.ToTable("DataSources", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_DataSources_AccessMode", "[AllowRead] = CAST(1 AS bit) OR [AllowWrite] = CAST(1 AS bit)");

                            t.HasCheckConstraint("CK_DataSources_ConnectionSecretReference", "[ConnectionSecretReference] LIKE N'secretref://%'");

                            t.HasCheckConstraint("CK_DataSources_MaxConcurrency", "[MaxConcurrency] >= 1 AND [MaxConcurrency] <= 1024");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.DataSourceRegistrationAuditRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BindingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("BindingVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.HasKey("TenantId", "CompanyId", "Id");

                    b.HasIndex("TenantId", "ActorUserId");

                    b.HasIndex("TenantId", "CompanyId", "DataSourceId");

                    b.HasIndex("TenantId", "CompanyId", "OperationId")
                        .IsUnique();

                    b.ToTable("DataSourceRegistrationAudits", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_DataSourceRegistrationAudits_BindingVersion", "[BindingVersion] > 0");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.DataSourceSecretBindingRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanonicalReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("TenantId", "CompanyId", "Id");

                    b.HasIndex("TenantId", "CompanyId", "CanonicalReference")
                        .IsUnique();

                    b.ToTable("DataSourceSecretBindings", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_DataSourceSecretBindings_Version", "[Version] > 0");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupAccountCoverageGapRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConnectorAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ListenerEpoch")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset>("OpenedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("RecordedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("TenantId", "CompanyId", "ConnectorAccountId", "ListenerEpoch", "Reason");

                    b.ToTable("GroupAccountCoverageGaps", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_GroupAccountCoverageGaps_Values", "[ListenerEpoch] > 0 AND [Reason] IN ('listener-started','listener-expired','listener-stopped') AND [RecordedAtUtc] >= [OpenedAtUtc] AND DATEPART(tz,[OpenedAtUtc]) = 0 AND DATEPART(tz,[RecordedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupBindingRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConnectorAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("DeletionGeneration")
                        .HasColumnType("bigint");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ExternalAccountId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ExternalGroupId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("IdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength()
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PhysicalGroupHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength()
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "CompanyId", "Id");

                    b.HasIndex("IdentityHash")
                        .IsUnique();

                    b.HasIndex("PhysicalGroupHash")
                        .IsUnique();

                    b.HasIndex("TenantId", "CompanyId", "ConnectorAccountId");

                    b.ToTable("GroupBindings", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_GroupBindings_Role", "[Role] IN (1,2)");

                            t.HasCheckConstraint("CK_GroupBindings_Versions", "[Version] > 0 AND [DeletionGeneration] >= 0");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupConnectorAccountRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalAccountId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("GitCommit")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("IdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength()
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PackageVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("QualificationJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "CompanyId", "Id");

                    b.HasIndex("IdentityHash")
                        .IsUnique();

                    b.ToTable("GroupConnectorAccounts", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_GroupConnectorAccounts_Qualification", "ISJSON([QualificationJson]) = 1");

                            t.HasCheckConstraint("CK_GroupConnectorAccounts_Version", "[Version] > 0");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupCoverageGapRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BindingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AfterCommittedSequence")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("OpenedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset?>("ReconnectedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("TenantId", "CompanyId", "BindingId", "Id");

                    b.HasIndex("TenantId", "CompanyId", "BindingId", "OpenedAtUtc");

                    b.ToTable("GroupCoverageGaps", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_GroupCoverageGaps_Values", "[AfterCommittedSequence] >= 0 AND DATEPART(tz,[OpenedAtUtc]) = 0 AND ([ReconnectedAtUtc] IS NULL OR ([ReconnectedAtUtc] >= [OpenedAtUtc] AND DATEPART(tz,[ReconnectedAtUtc]) = 0))");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupIngressInboxRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BindingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CommittedSequence")
                        .HasColumnType("bigint");

                    b.Property<long>("CredentialEpoch")
                        .HasColumnType("bigint");

                    b.Property<long>("DeletionGeneration")
                        .HasColumnType("bigint");

                    b.Property<long>("GrantVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SourceVersion")
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "CompanyId", "BindingId", "EventId");

                    b.HasIndex("TenantId", "CompanyId", "ServiceId");

                    b.HasIndex("TenantId", "CompanyId", "BindingId", "CommittedSequence")
                        .IsUnique();

                    b.HasIndex("TenantId", "CompanyId", "BindingId", "MessageId", "Revision");

                    b.ToTable("GroupIngressInbox", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_GroupIngressInbox_Values", "[Revision] > 0 AND [CommittedSequence] > 0 AND [SourceVersion] > 0 AND [DeletionGeneration] >= 0 AND [CredentialEpoch] > 0 AND [GrantVersion] > 0 AND DATEPART(tz,[ReceivedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupIngressOutboxRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BindingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("CommittedSequence")
                        .HasColumnType("bigint");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PublishAttempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "CompanyId", "BindingId", "Id");

                    b.HasIndex("PublishedAtUtc", "AvailableAtUtc");

                    b.HasIndex("TenantId", "CompanyId", "BindingId", "MessageId", "Revision")
                        .IsUnique();

                    b.ToTable("GroupIngressOutbox", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_GroupIngressOutbox_Values", "[Revision] > 0 AND [CommittedSequence] > 0 AND [PublishAttempts] >= 0 AND DATEPART(tz,[AvailableAtUtc]) = 0 AND ([PublishedAtUtc] IS NULL OR DATEPART(tz,[PublishedAtUtc]) = 0)");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupIngressReceiptRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BindingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventIdentityHash")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength()
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset>("CommittedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("CredentialEpoch")
                        .HasColumnType("bigint");

                    b.Property<string>("EnvelopeSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength()
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ExternalRevisionEventId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long>("ListenerEpoch")
                        .HasColumnType("bigint");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantId", "CompanyId", "BindingId", "EventIdentityHash");

                    b.HasIndex("TenantId", "CompanyId", "ServiceId");

                    b.HasIndex("TenantId", "CompanyId", "BindingId", "MessageId", "Revision");

                    b.ToTable("GroupIngressReceipts", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_GroupIngressReceipts_Values", "[Revision] > 0 AND [CredentialEpoch] > 0 AND [ListenerEpoch] > 0 AND DATEPART(tz,[CommittedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupListenerCommandReceiptRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CredentialEpoch")
                        .HasColumnType("bigint");

                    b.Property<Guid>("Nonce")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Changed")
                        .HasColumnType("bit");

                    b.Property<string>("CommandSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength()
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset>("CommittedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ConnectorAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CoverageRecorded")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("HeartbeatAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("ListenerEpoch")
                        .HasColumnType("bigint");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantId", "CompanyId", "ServiceId", "CredentialEpoch", "Nonce");

                    b.HasIndex("TenantId", "CompanyId", "ConnectorAccountId");

                    b.ToTable("GroupListenerCommandReceipts", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_GroupListenerCommandReceipts_Values", "[CredentialEpoch] > 0 AND [ListenerEpoch] > 0 AND [Operation] IN (1,2,3) AND [ExpiresAtUtc] >= [HeartbeatAtUtc] AND [CommittedAtUtc] >= [HeartbeatAtUtc] AND DATEPART(tz,[HeartbeatAtUtc]) = 0 AND DATEPART(tz,[ExpiresAtUtc]) = 0 AND DATEPART(tz,[CommittedAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupListenerLeaseRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConnectorAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Epoch")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("HeartbeatAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantId", "CompanyId", "ConnectorAccountId");

                    b.ToTable("GroupListenerLeases", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_GroupListenerLeases_Values", "[Epoch] > 0 AND [ExpiresAtUtc] >= [HeartbeatAtUtc] AND DATEPART(tz,[ExpiresAtUtc]) = 0 AND DATEPART(tz,[HeartbeatAtUtc]) = 0");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupMessageRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BindingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalMessageId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("IdentityHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength()
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("TenantId", "CompanyId", "BindingId", "Id");

                    b.HasIndex("TenantId", "CompanyId", "BindingId", "IdentityHash")
                        .IsUnique();

                    b.ToTable("GroupMessages", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupMessageRevisionRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BindingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CommittedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("CommittedSequence")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentKeyId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("ContentSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength()
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long>("DeletionGeneration")
                        .HasColumnType("bigint");

                    b.Property<string>("ExternalRevisionEventId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<bool>("IsHistoricalBackfill")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("ProtectedContent")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ReplyToMessageId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<long>("SourceVersion")
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "CompanyId", "BindingId", "MessageId", "Revision");

                    b.HasIndex("TenantId", "CompanyId", "BindingId", "CommittedSequence")
                        .IsUnique();

                    b.ToTable("GroupMessageRevisions", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_GroupMessageRevisions_Content", "DATALENGTH([ProtectedContent]) BETWEEN 29 AND 65536");

                            t.HasCheckConstraint("CK_GroupMessageRevisions_Utc", "DATEPART(tz,[OccurredAtUtc]) = 0 AND DATEPART(tz,[CommittedAtUtc]) = 0");

                            t.HasCheckConstraint("CK_GroupMessageRevisions_Values", "[Revision] > 0 AND [CommittedSequence] > 0 AND [SourceVersion] > 0 AND [DeletionGeneration] >= 0 AND [Kind] IN (1,2,3,4)");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupReaderGrantRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BindingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "CompanyId", "UserId", "BindingId");

                    b.HasIndex("TenantId", "CompanyId", "BindingId");

                    b.ToTable("GroupReaderGrants", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_GroupReaderGrants_Version", "[Version] > 0");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupServiceGrantRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BindingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capability")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "CompanyId", "ServiceId", "BindingId", "Capability");

                    b.HasIndex("TenantId", "CompanyId", "BindingId");

                    b.ToTable("GroupServiceGrants", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_GroupServiceGrants_Values", "[Version] > 0 AND [Capability] IN (1,2,3)");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupServiceRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CredentialEpoch")
                        .HasColumnType("bigint");

                    b.Property<string>("CredentialReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("TenantId", "CompanyId", "Id");

                    b.ToTable("GroupServices", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_GroupServices_Epoch", "[CredentialEpoch] > 0");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupSourceStateRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BindingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CommittedSequence")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("FirstPendingAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastPendingAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("ScheduledThroughSequence")
                        .HasColumnType("bigint");

                    b.HasKey("TenantId", "CompanyId", "BindingId");

                    b.ToTable("GroupSourceStates", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_GroupSourceStates_Cursors", "[CommittedSequence] >= [ScheduledThroughSequence] AND [ScheduledThroughSequence] >= 0");

                            t.HasCheckConstraint("CK_GroupSourceStates_Pending", "([FirstPendingAtUtc] IS NULL AND [LastPendingAtUtc] IS NULL) OR ([FirstPendingAtUtc] IS NOT NULL AND [LastPendingAtUtc] IS NOT NULL AND [FirstPendingAtUtc] <= [LastPendingAtUtc] AND DATEPART(tz,[FirstPendingAtUtc]) = 0 AND DATEPART(tz,[LastPendingAtUtc]) = 0)");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.PlatformMetadataRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Key");

                    b.ToTable("PlatformMetadata", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.PlatformUserRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IdentityProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "IdentityProvider", "Subject")
                        .IsUnique();

                    b.ToTable("Users", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.RoleAssignmentRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.HasKey("TenantId", "CompanyId", "UserId", "RoleKey");

                    b.ToTable("RoleAssignments", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskCheckpointRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenantId", "CompanyId", "TaskId", "StepId", "Version");

                    b.ToTable("TaskCheckpoints", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskDependencyRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DependsOnStepId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantId", "CompanyId", "TaskId", "StepId", "DependsOnStepId");

                    b.HasIndex("TenantId", "CompanyId", "TaskId", "DependsOnStepId");

                    b.ToTable("TaskDependencies", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskDispatchRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AcknowledgedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Attempt")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CheckpointVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<DateTimeOffset?>("DeadLetteredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Pending");

                    b.HasKey("TenantId", "CompanyId", "TaskId", "StepId", "MessageId");

                    b.HasIndex("TenantId", "CompanyId", "State", "AvailableAtUtc");

                    b.HasIndex("TenantId", "CompanyId", "TaskId", "StepId", "Attempt")
                        .IsUnique();

                    b.ToTable("TaskDispatches", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskEventRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StepId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantId", "CompanyId", "TaskId", "Sequence");

                    b.HasIndex("TenantId", "CompanyId", "TaskId", "StepId");

                    b.ToTable("TaskEvents", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("WaitReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("TenantId", "CompanyId", "Id");

                    b.HasIndex("TenantId", "CompanyId", "CreatedByUserId");

                    b.HasIndex("TenantId", "CompanyId", "Status");

                    b.HasIndex("TenantId", "CompanyId", "CreatedByUserId", "CreatedAtUtc", "Id")
                        .IsDescending(false, false, false, true, true)
                        .HasDatabaseName("IX_Tasks_OwnerHistory");

                    b.ToTable("Tasks", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskStepExecutionRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("DeadLetteredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastFailureClass")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset?>("LeaseAcquiredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("LeaseFenceToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LeaseOwnerId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.HasKey("TenantId", "CompanyId", "TaskId", "StepId");

                    b.HasIndex("TenantId", "CompanyId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "CompanyId", "LeaseExpiresAtUtc");

                    b.ToTable("TaskStepExecutions", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskStepRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("StepKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.HasKey("TenantId", "CompanyId", "TaskId", "Id");

                    b.HasIndex("TenantId", "CompanyId", "TaskId", "StepKey")
                        .IsUnique();

                    b.ToTable("TaskSteps", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskSubmissionIntentRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("InputFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength()
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("InputVersion")
                        .HasColumnType("int");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("TenantId", "CompanyId", "UserId", "OperationId");

                    b.HasIndex("TenantId", "CompanyId", "UserId", "CreatedAtUtc", "OperationId")
                        .IsDescending(false, false, false, true, true);

                    b.ToTable("TaskSubmissionIntents", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_TaskSubmissionIntents_Input", "[InputVersion] = 1 AND [MaxAttempts] = 3");

                            t.HasCheckConstraint("CK_TaskSubmissionIntents_Lifetime", "[ExpiresAtUtc] = DATEADD(hour,24,[CreatedAtUtc])");

                            t.HasCheckConstraint("CK_TaskSubmissionIntents_Question", "DATALENGTH([Question]) BETWEEN 2 AND 8000");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.CompanyAdministratorAuditRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyMembershipRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.CompanyMembershipAccessAuditRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyMembershipRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.CompanyMembershipRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.DataSourceFailoverOperationPolicyRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.DataSourceRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.DataSourceRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.DataSourceRegistrationAuditRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.DataSourceRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.DataSourceSecretBindingRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupAccountCoverageGapRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.GroupConnectorAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "ConnectorAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupBindingRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.GroupConnectorAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "ConnectorAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupConnectorAccountRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupCoverageGapRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.GroupBindingRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "BindingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupIngressInboxRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.GroupServiceRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.GroupIngressOutboxRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "BindingId", "EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.GroupMessageRevisionRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "BindingId", "MessageId", "Revision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupIngressOutboxRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.GroupMessageRevisionRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "BindingId", "MessageId", "Revision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupIngressReceiptRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.GroupServiceRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.GroupMessageRevisionRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "BindingId", "MessageId", "Revision")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupListenerCommandReceiptRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.GroupConnectorAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "ConnectorAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.GroupServiceRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupListenerLeaseRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.GroupConnectorAccountRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "ConnectorAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupMessageRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.GroupBindingRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "BindingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupMessageRevisionRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.GroupMessageRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "BindingId", "MessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupReaderGrantRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.GroupBindingRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "BindingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyMembershipRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupServiceGrantRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.GroupBindingRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "BindingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.GroupServiceRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupServiceRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.GroupSourceStateRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.GroupBindingRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "BindingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.RoleAssignmentRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyMembershipRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskCheckpointRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.TaskStepRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "TaskId", "StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskDependencyRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.TaskStepRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "TaskId", "DependsOnStepId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.TaskStepRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "TaskId", "StepId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskDispatchRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.TaskStepRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "TaskId", "StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskEventRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.TaskRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.TaskStepRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "TaskId", "StepId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyMembershipRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskStepExecutionRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.TaskStepRecord", null)
                        .WithOne()
                        .HasForeignKey("MinhHuy.AIOffice.Platform.Persistence.TaskStepExecutionRecord", "TenantId", "CompanyId", "TaskId", "StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskStepRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.TaskRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskSubmissionIntentRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyMembershipRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
