// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinhHuy.AIOffice.Platform.Persistence;

#nullable disable

namespace MinhHuy.AIOffice.Platform.Persistence.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20261009031227_AddOwnerTaskHistory")]
    partial class AddOwnerTaskHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("aioffice")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.CompanyAdministratorAuditRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AfterAdministrator")
                        .HasColumnType("bit");

                    b.Property<string>("AfterRolesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("AfterVersion")
                        .HasColumnType("bigint");

                    b.Property<bool>("BeforeAdministrator")
                        .HasColumnType("bit");

                    b.Property<string>("BeforeRolesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("BeforeVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantId", "CompanyId", "Id");

                    b.HasIndex("TenantId", "ActorUserId");

                    b.HasIndex("TenantId", "CompanyId", "OperationId")
                        .IsUnique();

                    b.HasIndex("TenantId", "CompanyId", "TargetUserId");

                    b.ToTable("CompanyAdministratorAudits", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_CompanyAdministratorAudits_Versions", "[BeforeVersion] > 0 AND [AfterVersion] >= [BeforeVersion]");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.CompanyMembershipAccessAuditRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AfterActive")
                        .HasColumnType("bit");

                    b.Property<long>("AfterVersion")
                        .HasColumnType("bigint");

                    b.Property<bool>("BeforeActive")
                        .HasColumnType("bit");

                    b.Property<long>("BeforeVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantId", "CompanyId", "Id");

                    b.HasIndex("TenantId", "ActorUserId");

                    b.HasIndex("TenantId", "CompanyId", "OperationId")
                        .IsUnique();

                    b.HasIndex("TenantId", "CompanyId", "TargetUserId");

                    b.ToTable("CompanyMembershipAccessAudits", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_CompanyMembershipAccessAudits_Versions", "[BeforeVersion] > 0 AND [AfterVersion] >= [BeforeVersion]");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.CompanyMembershipRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("TenantId", "CompanyId", "UserId");

                    b.HasIndex("TenantId", "UserId");

                    b.ToTable("CompanyMemberships", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_CompanyMemberships_Version", "[Version] > 0");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique();

                    b.ToTable("Companies", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.CustomerSlaPolicyRevisionRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("PolicyVersion")
                        .HasColumnType("bigint");

                    b.Property<long>("AuthorityVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("EffectiveAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PriorityCeiling")
                        .HasColumnType("int");

                    b.Property<int>("SchedulerPriority")
                        .HasColumnType("int");

                    b.Property<string>("ServiceLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TenantId", "CompanyId", "UserId", "PolicyVersion");

                    b.HasIndex("TenantId", "CompanyId", "UserId", "EffectiveAtUtc")
                        .HasDatabaseName("IX_CustomerSlaPolicyRevisions_Current");

                    b.ToTable("CustomerSlaPolicyRevisions", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.DataSourceFailoverOperationPolicyRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Operation")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<DateTimeOffset>("EffectiveAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("TenantId", "CompanyId", "DataSourceId", "Operation", "Version");

                    b.HasIndex("TenantId", "CompanyId", "DataSourceId", "Operation", "EffectiveAt");

                    b.ToTable("DataSourceFailoverOperationPolicies", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_DataSourceFailoverOperationPolicies_Version", "[Version] > 0");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.DataSourceRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AllowRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("AllowWrite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ConnectionSecretReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LogicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MaxConcurrency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.HasKey("TenantId", "CompanyId", "Id");

                    b.HasIndex("TenantId", "CompanyId", "LogicalName")
                        .IsUnique();

                    b.ToTable("DataSources", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_DataSources_AccessMode", "[AllowRead] = CAST(1 AS bit) OR [AllowWrite] = CAST(1 AS bit)");

                            t.HasCheckConstraint("CK_DataSources_ConnectionSecretReference", "[ConnectionSecretReference] LIKE N'secretref://%'");

                            t.HasCheckConstraint("CK_DataSources_MaxConcurrency", "[MaxConcurrency] >= 1 AND [MaxConcurrency] <= 1024");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.DataSourceRegistrationAuditRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BindingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("BindingVersion")
                        .HasColumnType("bigint");

                    b.Property<Guid>("DataSourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.HasKey("TenantId", "CompanyId", "Id");

                    b.HasIndex("TenantId", "ActorUserId");

                    b.HasIndex("TenantId", "CompanyId", "DataSourceId");

                    b.HasIndex("TenantId", "CompanyId", "OperationId")
                        .IsUnique();

                    b.ToTable("DataSourceRegistrationAudits", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_DataSourceRegistrationAudits_BindingVersion", "[BindingVersion] > 0");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.DataSourceSecretBindingRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanonicalReference")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("Version")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(1L);

                    b.HasKey("TenantId", "CompanyId", "Id");

                    b.HasIndex("TenantId", "CompanyId", "CanonicalReference")
                        .IsUnique();

                    b.ToTable("DataSourceSecretBindings", "aioffice", t =>
                        {
                            t.HasCheckConstraint("CK_DataSourceSecretBindings_Version", "[Version] > 0");
                        });
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.PlatformMetadataRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Key");

                    b.ToTable("PlatformMetadata", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.PlatformUserRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("IdentityProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "IdentityProvider", "Subject")
                        .IsUnique();

                    b.ToTable("Users", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.RoleAssignmentRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.HasKey("TenantId", "CompanyId", "UserId", "RoleKey");

                    b.ToTable("RoleAssignments", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskCheckpointRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TenantId", "CompanyId", "TaskId", "StepId", "Version");

                    b.ToTable("TaskCheckpoints", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskDependencyRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DependsOnStepId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantId", "CompanyId", "TaskId", "StepId", "DependsOnStepId");

                    b.HasIndex("TenantId", "CompanyId", "TaskId", "DependsOnStepId");

                    b.ToTable("TaskDependencies", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskDispatchRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AcknowledgedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Attempt")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("AvailableAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("CheckpointVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<DateTimeOffset?>("DeadLetteredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Pending");

                    b.HasKey("TenantId", "CompanyId", "TaskId", "StepId", "MessageId");

                    b.HasIndex("TenantId", "CompanyId", "State", "AvailableAtUtc");

                    b.HasIndex("TenantId", "CompanyId", "TaskId", "StepId", "Attempt")
                        .IsUnique();

                    b.ToTable("TaskDispatches", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskEventRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StepId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TenantId", "CompanyId", "TaskId", "Sequence");

                    b.HasIndex("TenantId", "CompanyId", "TaskId", "StepId");

                    b.ToTable("TaskEvents", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("WaitReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("TenantId", "CompanyId", "Id");

                    b.HasIndex("TenantId", "CompanyId", "CreatedByUserId");

                    b.HasIndex("TenantId", "CompanyId", "Status");

                    b.HasIndex("TenantId", "CompanyId", "CreatedByUserId", "CreatedAtUtc", "Id")
                        .IsDescending(false, false, false, true, true)
                        .HasDatabaseName("IX_Tasks_OwnerHistory");

                    b.ToTable("Tasks", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskStepExecutionRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StepId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("DeadLetteredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastFailureClass")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset?>("LeaseAcquiredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("LeaseFenceToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<Guid?>("LeaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LeaseOwnerId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("NextAttemptAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.HasKey("TenantId", "CompanyId", "TaskId", "StepId");

                    b.HasIndex("TenantId", "CompanyId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "CompanyId", "LeaseExpiresAtUtc");

                    b.ToTable("TaskStepExecutions", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskStepRecord", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("StepKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.HasKey("TenantId", "CompanyId", "TaskId", "Id");

                    b.HasIndex("TenantId", "CompanyId", "TaskId", "StepKey")
                        .IsUnique();

                    b.ToTable("TaskSteps", "aioffice");
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.CompanyAdministratorAuditRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyMembershipRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.CompanyMembershipAccessAuditRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyMembershipRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.CompanyMembershipRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.DataSourceFailoverOperationPolicyRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.DataSourceRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.DataSourceRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.DataSourceRegistrationAuditRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.PlatformUserRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.DataSourceRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "DataSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.DataSourceSecretBindingRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.RoleAssignmentRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyMembershipRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskCheckpointRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.TaskStepRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "TaskId", "StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskDependencyRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.TaskStepRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "TaskId", "DependsOnStepId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.TaskStepRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "TaskId", "StepId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskDispatchRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.TaskStepRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "TaskId", "StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskEventRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.TaskRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.TaskStepRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "TaskId", "StepId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.CompanyMembershipRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskStepExecutionRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.TaskStepRecord", null)
                        .WithOne()
                        .HasForeignKey("MinhHuy.AIOffice.Platform.Persistence.TaskStepExecutionRecord", "TenantId", "CompanyId", "TaskId", "StepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MinhHuy.AIOffice.Platform.Persistence.TaskStepRecord", b =>
                {
                    b.HasOne("MinhHuy.AIOffice.Platform.Persistence.TaskRecord", null)
                        .WithMany()
                        .HasForeignKey("TenantId", "CompanyId", "TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
